version: '3.8'
services: 
  node-web:
    build: .
    ports:
      - "8080:8080"
    depends_on: 
      - database
    networks:
      - nginx_network
  database:
    image: mongo:4.4.10
    ports:
      - 27017:27017
    restart: always 
    volumes: 
      - my_data:/data/db
    networks:
      - nginx_network
volumes: 
  my_data:

networks:
  nginx_network:
    external: true