version: '3.8'
services: 
  node-web:
    build: .
    ports: 
      - "8080:8080"
    depends_on: 
      - database
  database:
    image: mongo:4.4.10
    ports:
      - 27017:27017
    restart: always 
    volumes: 
      - my_data:/data/db 
volumes: 
  my_data: 